## 导入相关包

In [5]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# 一、基础

## 1、张量  
简单讲，张量就是对标量矢量以及更高维度变量的统称，是用一种统一的方式来处理多线性映射。  
一维数组称为矢量，二维方阵称为二阶张量，3维方阵称为三阶张量

### 1.1创建张量

***补充  
tensorflow中以数据流图为基础，所以在进行操作时要首先创建图的session，具体后面会讲  
并且一般是使用上下文管理器--with,防忘记关闭session，浪费资源***

#### 1.1.1 创建制定维度的零向量

In [6]:
with tf.Session() as sess:
    zero_tensor = tf.zeros((2,3))
    print(sess.run(zero_tensor))    # sess.run() -- 在图中执行某个操作：获取变量的值，进行某个运算，更改变量的值，

[[0. 0. 0.]
 [0. 0. 0.]]


#### 1.1.2 创建指定维度的全1张量

In [7]:
with tf.Session() as sess:
    ones_tsr = tf.ones([2,3])
    print(ones_tsr.eval())         # 获取某个数据的值，可以直接用sess.run()，也可以用这种方法，XX.eval()   

[[1. 1. 1.]
 [1. 1. 1.]]


#### 1.1.3 创建使用指定数字填充指定纬度的张量

In [9]:
with tf.Session() as sess:
    fill_tsr = tf.fill((3,4),6)     # 这里指定纬度，使用[]和（）都可以   
    print(sess.run(fill_tsr))

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


#### 1.1.4 使用已经存在常数张量创建张量

In [11]:
with tf.Session() as sess:
    constant_tsr = tf.constant([[2,3],[5,6],[6,7]])
    print(constant_tsr.eval())

[[2 3]
 [5 6]
 [6 7]]


#### 1.1.5 创建相同纬度张量

In [12]:
with tf.Session() as sess:
    zeros_tsr = tf.zeros_like(constant_tsr)     # 创建一个全0 的与contant_tsr相同维度的张量
    ones_tsr = tf.ones_like(constant_tsr)       # 创建一个全1 的与contant_tsr相同维度的张量
    print(sess.run(zeros_tsr))
    print(sess.run(ones_tsr))

[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


#### 1.1.6 创建指定数据间隔的张量  
 - linspace()包含两个端点 且端点值只支持浮点型，range()不含右端点

In [18]:
with tf.Session() as sess:
    linear_tsr = tf.linspace(start=0.,stop=1.,num = 3,name= 'linear_tsr')     #在tensorflow中创建变量，张量，占位等等
    print(sess.run(linear_tsr))                                               #最好赋上name属性，在后期查看数据流图有大用
    integer_seq_tsr = tf.range(start = 6,limit=15,delta = 3,name='integer_seq_tsr')    
    print(sess.run(integer_seq_tsr))

[0.  0.5 1. ]
[ 6  9 12]


#### 1.1.7 创建随机数字填充的张量

In [20]:
with tf.Session() as sess:
    #用random_uniform()生成均匀分布随机数
    randunif_tsr = tf.random_uniform([3,3],minval = 1,maxval = 4 ,name='randunif_tsr')
     #用random_normal()生成正太分布随机数 mean:平均值，stddev:标准差
    randnorm_tsr = tf.random_normal([3,3],mean = 0.0,stddev=1.0,name='randnorm_tsr')
       #truncated_normal()生成指定边界的正态分布的随机数  边界：期望到两个标准差之间的区间
    runcnorm_tsr = tf.truncated_normal([3,3],mean=0.0,stddev=1.0,name='runcnorm_tsr')
    print('random_uniform : \n',randunif_tsr.eval())
    print('random_normal :\n',randnorm_tsr.eval())
    print('truncated_normal : \n',runcnorm_tsr.eval())

random_uniform : 
 [[3.374119  1.3865707 3.4835718]
 [1.8780107 3.9743133 3.0297832]
 [1.304082  3.538796  1.9242141]]
random_normal :
 [[ 0.3259223  -1.0879962  -0.30286068]
 [ 0.33060467  0.35165852 -0.19939163]
 [ 1.3577285  -0.3525623  -0.6351039 ]]
truncated_normal : 
 [[ 0.30716732 -0.06338297 -0.60334986]
 [-0.08352657  0.80927795  0.73871243]
 [-1.4190829  -0.72404945  1.3619605 ]]


#### 1.1.8 获得一个失序的张量  
 - 仅仅是对最低纬度的顺序进行乱序重排，例如一个一维，则是对里面元素的重排，如果是二维，则是对行元素的重排

In [47]:
with tf.Session() as sess:
    demo1_tsr = tf.constant([1,2,3,4,5])
    demo_tsr = tf.constant([[2,3,4,9],[5,6,7,8],[11,12,13,14]])       # 生成一个测试张量
    print(sess.run(demo_tsr))
    shuffled_output = tf.random_shuffle(demo_tsr)                     # 失序
    shuffled1_output = tf.random_shuffle(demo1_tsr)
    print('多维原始：\n',sess.run(demo_tsr))
    print('多维打乱：\n',sess.run(shuffled_output))
    print('一维原始：',sess.run(demo1_tsr))
    print('一维打乱：',sess.run(shuffled1_output))

[[ 2  3  4  9]
 [ 5  6  7  8]
 [11 12 13 14]]
多维原始：
 [[ 2  3  4  9]
 [ 5  6  7  8]
 [11 12 13 14]]
多维打乱：
 [[ 5  6  7  8]
 [11 12 13 14]
 [ 2  3  4  9]]
一维原始： [1 2 3 4 5]
一维打乱： [1 3 5 2 4]


#### 1.1.9 随机裁剪指定纬度的元素

In [54]:
with tf.Session() as sess:
    demo_tsr = tf.constant(np.arange(12).reshape([3,4]))         # 生成一个测试张量
    croped_output = tf.random_crop(demo_tsr,[2,2])              # 裁剪
    print(sess.run(demo_tsr))
    print(sess.run(croped_output))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]


### 1.2 转化为张量

#### 1.2.1 numpy数组转化为张量  
- 除了可以在创建张量时用numpy数组直接赋值，还可以使用convert_to_tensor,将numpy数组转化为张量  
- 列表也是可以转化的

In [56]:
with tf.Session() as sess:
    arr_np = np.arange(12).reshape((3,4))            #  创建一个numpy数组
    print(type(arr_np))
    arr_tsr = tf.convert_to_tensor(arr_np)
    print(type(arr_tsr))

<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


## 2、tensorflow 基本概念

### 2.1 变量 (Variable)
- 创建Variable，需将一个tensor传递给Variable()构造函数
- 需要指定tensor的shape，最好为name 属性赋上值

In [67]:
with tf.Session() as sess:
    demo_variable = tf.Variable(tf.zeros([3,3]),name='demo')
    #sess.run(demo_variable.initializer)      # 初始化变量，这是初始化这一个变量，
    sess.run(tf.global_variables_initializer())    #还可以一次性初始化全部变量
    print(sess.run(demo_variable))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


- 变量赋值  
tensorflow中使用assign为变量赋值
       

In [70]:
with tf.Session() as sess:
    demo_variable = tf.Variable(tf.random_normal(shape=[]),dtype=tf.float32,name = 'demo_variable')  # 创建一个变量，随机为其赋值
    sess.run(tf.global_variables_initializer())   #初始化变量
    print(sess.run(demo_variable))
    demo_variable = demo_variable.assign(4)    # 为变量赋值
    print(demo_variable.eval())
    sess.run(demo_variable)
    print(demo_variable.eval())

-0.96191704
4.0
4.0


### 2.2 占位 （paceholder）  
- 数据的入口  
- 需要指定数据类型和数据的结构
- session运行中为其提供数据，数据通过这里进入模型

In [98]:
with tf.Session() as sess:
  
    demo_place = tf.placeholder(shape=[1],dtype=tf.float32,name='demo_place') # 这里需要指定shape和数据类型和name
  

### 2.3 图 （graph）  
- tensorflow是基于数据流图的，tensorflow程序通常被组织成一个图的构建和图的执行阶段
- 程序中存在一个默认图，也可以显示声明图

In [99]:
g1 = tf.Graph()       # 显示创建一个图
print(g1)    
g2 = tf.Graph()      # 创建另一个图
print(g2)
print(tf.get_default_graph())    # 获取默认图，创建图，对默认图并没有影响


- 操作  
数据的操作被局限在一个图中

In [107]:
# 定义一个图
g1 = tf.Graph()
g2 = tf.Graph()

#将图1设置为默认图，则在下面的with语句块中，所做操作为在图1 中的操作
with g1.as_default():
    a = tf.constant(10,name='a')
    b = tf.constant(20,name='b')
    c = tf.add(a,b,name='c')
# 图2
with g2.as_default():
    a = tf.constant(5,name='a')
    b = tf.constant(4,name='b')
    d = tf.add(a,b,name='d')
# 为session指定图
with tf.Session(graph=g1) as sess:
    print(sess.run(c))
    print(c.eval())

with tf.Session(graph=g2) as sess:
    print(sess.run(d))
    print(d.eval())

30
30
9
9


### 2.4 会话 （session）  
- 会话持有并管理tensorflow程序运行时的所有资源，一切计算都是在会话的基础上
- 会话管理两种方式：
  -- 明确的调用会话的生成函数和关闭会话函数
  -- 上下文管理机制自动释放所有资源


In [ ]:
#第一种  
sess = tf.Session()　　　#　声明会话

#...执行操作  
sess.close()       # 关闭会话

In [ ]:
# 第二种  不再需要关闭会话
with tf.Session() as sess:
    sess.run(...)

**图（graph）与会话（session）的关系**
 - 一个图可以对应多个会话
 - 一个会话只能对应一个图


In [108]:
# 定义两个图
g1 = tf.Graph()
g2 = tf.Graph()
# 创建两个会话，并同时绑定到图1
sess1 = tf.Session(graph=g1)
sess2 = tf.Session(graph=g1)
#将图1设置为默认图，则在下面的with语句块中，所做操作为在图1 中的操作
with g1.as_default():
    a = tf.constant(10,name='a')
    b = tf.constant(20,name='b')
    c = tf.add(a,b,name='c')
# 图2
with g2.as_default():
    a = tf.constant(5,name='a')
    b = tf.constant(4,name='b')
    d = tf.add(a,b,name='d')
print(sess1.run(c))
print(sess2.run(c))

30
30
